import { describe, expect, it } from "vitest";

import { reportMarkdown, type ReportExportMeta } from "./report-markdown";
import type { SessionReport } from "./types";

// F-48 and F-03b on the markdown export, and the pin that matters most: every
// report stored since v0.1 lacks key_span and carries empty per-dimension
// lists, and its export must not move by one byte. The v0.8 export shipped
// against current-shape fixtures only and 404d every existing production
// report; this file exists so that class of failure has a test to fail.

const META: ReportExportMeta = {
  sessionNumber: 2,
  sessionDate: "2026-07-30",
  roleTitle: "Staff Engineer",
  generatedDate: "2026-08-05",
  dimensions: [
    { key: "story", name: "Story structure" },
    { key: "delivery", name: "Executive delivery" },
  ],
};

const STORY_RATIONALE =
  "The candidate structures the answer around a measurable outcome. The setup names the stakeholder and the constraint before the action. The close returns to the number.";

// Exactly the shape the worker stored before F-03 and F-48: no key_span, no
// per-dimension strengths or weaknesses keys at all. The cast is the point.
const OLD_STORED = {
  session_id: "session-2",
  verdict: "approaching",
  overall_score: 3.6,
  dimension_scores: [
    {
      dimension_key: "story",
      score: 4.1,
      rationale: STORY_RATIONALE,
      evidence_quotes: ['"I reduced the queue by half."', '"The customer renewed early."'],
    },
    {
      dimension_key: "delivery",
      score: 3.1,
      rationale: "The answer was understandable but ran long.",
      evidence_quotes: [],
    },
  ],
  delivery_metrics: {
    wpm_overall: 142,
    wpm_timeline: [138, 146],
    silence_events: [{ start_s: 31, duration_s: 1.8 }],
    filler_count: 5,
    filler_rate_per_min: 1.2,
    f0_variance: 18.4,
    avg_response_latency_s: 1.1,
  },
  delivery_observations: [
    { at_s: 65, kind: "pace", note: "The conclusion accelerated.", conflicts_with_dsp: false },
  ],
  strengths: ["Specific outcomes"],
  gaps: ["Long setup"],
  next_drills: ["Give the result in the first sentence"],
  limits_note:
    "This report reflects one 20-minute session and cannot predict every interview outcome.",
} as unknown as SessionReport;

// The export of OLD_STORED as it left reportMarkdown before this change,
// captured from a run of the previous implementation, byte for byte.
const OLD_STORED_MARKDOWN = `# flightcheck session report

Session 2 | 2026-07-30 | Staff Engineer

## Approaching

Overall score: 3.6 / 5.0 | Ready bar: 4.0

## Story structure: 4.1 / 5.0

${STORY_RATIONALE}

### Evidence quotes

> "I reduced the queue by half."

> "The customer renewed early."

## Executive delivery: 3.1 / 5.0

The answer was understandable but ran long.

## Delivery metrics

- Pace: 142 WPM

- Fillers: 5 total, 1.2 per minute

- Pitch variance: 18.4

- Average response latency: 1.1s

- Pace timeline: 138 WPM, 146 WPM

### Silences

- 00:31: 1.8s

## Delivery observations

- 01:05: The conclusion accelerated.

## Strengths

- Specific outcomes

## Gaps

- Long setup

## Next drills

- Give the result in the first sentence

## Limits

This report reflects one 20-minute session and cannot predict every interview outcome.

Generated by flightcheck on 2026-08-05.
`;

/** OLD_STORED with per-dimension fields overridden on every dimension. */
function withDimensionFields(overrides: Record<string, unknown>): SessionReport {
  const base = OLD_STORED as unknown as { dimension_scores: Record<string, unknown>[] };
  return {
    ...OLD_STORED,
    dimension_scores: base.dimension_scores.map((score) => ({ ...score, ...overrides })),
  } as unknown as SessionReport;
}

describe("the old-shape export does not move", () => {
  it("renders a pre-F-48 stored report byte-identical to the previous export", () => {
    expect(reportMarkdown(OLD_STORED, META)).toBe(OLD_STORED_MARKDOWN);
  });

  it("renders the current worker defaults (null span, empty lists) to the same bytes", () => {
    const current = withDimensionFields({ key_span: null, strengths: [], weaknesses: [] });
    expect(reportMarkdown(current, META)).toBe(OLD_STORED_MARKDOWN);
  });
});

describe("the judge's span in the export", () => {
  it("emphasises the span in place, inside the untouched rationale", () => {
    const report = withDimensionFields({});
    (report.dimension_scores[0] as { key_span?: string }).key_span =
      "names the stakeholder and the constraint";
    const markdown = reportMarkdown(report, META);
    expect(markdown).toContain(
      "The setup **names the stakeholder and the constraint** before the action.",
    );
    // Everything around the markers is still the judge's paragraph.
    expect(markdown.replaceAll("**", "")).toBe(OLD_STORED_MARKDOWN.replaceAll("**", ""));
  });

  it("adds no markers when the span violates the substring contract", () => {
    const report = withDimensionFields({});
    (report.dimension_scores[0] as { key_span?: string }).key_span =
      "a paraphrase the judge never wrote";
    expect(reportMarkdown(report, META)).toBe(OLD_STORED_MARKDOWN);
  });
});

describe("per-dimension strengths and weaknesses in the export", () => {
  it("renders both lists under the dimension, between rationale and quotes", () => {
    const report = withDimensionFields({});
    Object.assign(report.dimension_scores[0] as object, {
      strengths: ["Leads with the result", "Names the stakeholder"],
      weaknesses: ["The setup runs long"],
    });
    const markdown = reportMarkdown(report, META);
    expect(markdown).toContain(
      "### What worked\n\n- Leads with the result\n- Names the stakeholder",
    );
    expect(markdown).toContain("### What held the score down\n\n- The setup runs long");
    const rationaleAt = markdown.indexOf(STORY_RATIONALE);
    const workedAt = markdown.indexOf("### What worked");
    const heldAt = markdown.indexOf("### What held the score down");
    const quotesAt = markdown.indexOf("### Evidence quotes");
    expect(rationaleAt).toBeGreaterThan(-1);
    expect(workedAt).toBeGreaterThan(rationaleAt);
    expect(heldAt).toBeGreaterThan(workedAt);
    expect(quotesAt).toBeGreaterThan(heldAt);
  });

  it("renders one list alone when the other is empty", () => {
    const report = withDimensionFields({ strengths: [], weaknesses: ["The setup runs long"] });
    const markdown = reportMarkdown(report, META);
    expect(markdown).not.toContain("### What worked");
    expect(markdown).toContain("### What held the score down\n\n- The setup runs long");
  });
});
