import { emphasiseRationale } from "@/lib/rationale";
import { formatTimestamp, VERDICT_LABELS } from "@/lib/report-format";
import type { DimensionScore, SessionReport } from "@/lib/types";
import { MAX_SCORE, READY_OVERALL } from "@/lib/verdict";

export interface ReportDimensionMeta {
  key: string;
  name: string;
}

export interface ReportExportMeta {
  sessionNumber: number;
  sessionDate: string;
  roleTitle: string;
  generatedDate: string;
  dimensions: ReportDimensionMeta[];
}

const dimensionName = (key: string, dimensions: ReportDimensionMeta[]): string =>
  dimensions.find((dimension) => dimension.key === key)?.name ?? key;

const dashList = (items: string[]): string => items.map((item) => `- ${item}`).join("\n");

const bullets = (items: string[]): string =>
  items.length === 0 ? "None recorded." : dashList(items);

// The judge's own span (F-48) is emphasised in place; the fallback adds no
// markers, because every report stored before the field existed must export
// byte-identical markdown (pinned in report-markdown-key-span.test.ts).
const rationaleBlock = (score: DimensionScore): string => {
  const parts = emphasiseRationale(score.rationale, score.key_span);
  return parts.source === "key_span"
    ? `${parts.before}**${parts.span}**${parts.after}`
    : score.rationale;
};

export function reportMarkdown(report: SessionReport, meta: ReportExportMeta): string {
  const metrics = report.delivery_metrics;
  const dimensions = report.dimension_scores.map((score) => {
    const quotes = score.evidence_quotes.map((quote) => `> ${quote}`).join("\n\n");
    // Declared required, but reports stored before F-03 omit the keys at
    // runtime: read defensively, render the sections only when they say
    // something, exactly as the screen does.
    const strengths = score.strengths ?? [];
    const weaknesses = score.weaknesses ?? [];
    return [
      `## ${dimensionName(score.dimension_key, meta.dimensions)}: ${score.score.toFixed(1)} / ${MAX_SCORE.toFixed(1)}`,
      rationaleBlock(score),
      strengths.length > 0 ? `### What worked\n\n${dashList(strengths)}` : "",
      weaknesses.length > 0 ? `### What held the score down\n\n${dashList(weaknesses)}` : "",
      quotes ? `### Evidence quotes\n\n${quotes}` : "",
    ].filter(Boolean).join("\n\n");
  }).join("\n\n");
  const silences = metrics.silence_events.length === 0
    ? "None recorded."
    : metrics.silence_events
        .map((event) => `- ${formatTimestamp(event.start_s)}: ${event.duration_s.toFixed(1)}s`)
        .join("\n");
  const observations = report.delivery_observations.length === 0
    ? "None recorded."
    : report.delivery_observations
        .map((observation) => `- ${formatTimestamp(observation.at_s)}: ${observation.note}`)
        .join("\n");

  return [
    "# flightcheck session report",
    `Session ${meta.sessionNumber} | ${meta.sessionDate} | ${meta.roleTitle}`,
    `## ${VERDICT_LABELS[report.verdict]}`,
    report.headline || null,
    `Overall score: ${report.overall_score.toFixed(1)} / ${MAX_SCORE.toFixed(1)} | Ready bar: ${READY_OVERALL.toFixed(1)}`,
    dimensions,
    "## Delivery metrics",
    `- Pace: ${Math.round(metrics.wpm_overall)} WPM`,
    `- Fillers: ${metrics.filler_count} total, ${metrics.filler_rate_per_min.toFixed(1)} per minute`,
    `- Pitch variance: ${metrics.f0_variance === null ? "n/a" : metrics.f0_variance.toFixed(1)}`,
    `- Average response latency: ${metrics.avg_response_latency_s === null ? "n/a" : `${metrics.avg_response_latency_s.toFixed(1)}s`}`,
    `- Pace timeline: ${metrics.wpm_timeline.length === 0 ? "n/a" : metrics.wpm_timeline.map((wpm) => `${Math.round(wpm)} WPM`).join(", ")}`,
    "### Silences",
    silences,
    "## Delivery observations",
    observations,
    "## Strengths",
    bullets(report.strengths),
    "## Gaps",
    bullets(report.gaps),
    "## Next drills",
    bullets(report.next_drills),
    "## Limits",
    report.limits_note,
    `Generated by flightcheck on ${meta.generatedDate}.`,
  ].filter((block) => block !== null && block !== "").join("\n\n") + "\n";
}
