import { bookmarkedItems } from "@/lib/paraphrase";
import { groupTurns } from "@/lib/transcript";
import type { SessionCoaching, SessionInsights, TranscriptSegment } from "@/lib/types";

export interface QaSet {
  ordinal: number;
  question: string | null;
  your_answer: string;
  better: string;
  why: string;
}

export function qaSets(
  segments: TranscriptSegment[],
  coaching: SessionCoaching | null,
): QaSet[] {
  const turns = groupTurns(segments);
  const candidatePositions = turns
    .map((turn, index) => ({ turn, index }))
    .filter(({ turn }) => turn.speaker === "candidate");
  if (
    coaching?.paraphrases !== null &&
    coaching?.paraphrases !== undefined &&
    coaching.paraphrases.turn_count !== candidatePositions.length
  ) return [];

  return bookmarkedItems(coaching?.paraphrases, coaching?.marks).flatMap(({ ordinal, item }) => {
    const candidate = candidatePositions[ordinal];
    if (candidate === undefined) return [];
    let question: string | null = null;
    for (let index = candidate.index - 1; index >= 0; index -= 1) {
      if (turns[index].speaker === "interviewer") {
        question = turns[index].text;
        break;
      }
    }
    return [{
      ordinal,
      question,
      your_answer: candidate.turn.text,
      better: item.suggestion,
      why: item.why,
    }];
  });
}

export interface SessionStudyMeta {
  sessionNumber: number;
  sessionDate: string;
  roleTitle: string | null;
  generatedDate: string;
}

const block = (...parts: string[]): string => parts.filter(Boolean).join("\n\n");
const quote = (value: string): string => `> ${value}`;

export function sessionStudyMarkdown(
  sets: QaSet[],
  insights: SessionInsights | null,
  meta: SessionStudyMeta,
): string {
  const saved = sets.map((set) => block(
    `## Q. ${set.question ?? "Question not captured"}`,
    `**Better answer.** ${set.better}`,
    `**What you said.** ${set.your_answer}`,
    `**Why.** ${set.why}`,
  )).join("\n\n");
  const core = (insights?.must_answer ?? []).map((item) => block(
    `### Q. ${item.question}`,
    item.model_answer,
    "_Generated by flightcheck from your session material._",
    ...item.based_on_quotes.map(quote),
  )).join("\n\n");
  const keep = (insights?.must_keep ?? []).map((item) => block(
    quote(item.said_verbatim),
    `**Better.** ${item.better}`,
    `**Why.** ${item.why}`,
  )).join("\n\n");
  const well = insights?.did_well.map((item) => `- ${item}`).join("\n") ?? "";
  const poorly = insights?.did_poorly.map((item) => `- ${item}`).join("\n") ?? "";
  const review = block(
    well ? block("### What went well", well) : "",
    poorly ? block("### What needs work", poorly) : "",
  );

  return `${block(
    "# flightcheck study notes",
    `Session ${meta.sessionNumber} | ${meta.sessionDate} | ${meta.roleTitle ?? "Interview role"}`,
    `Generated ${meta.generatedDate}.`,
    saved,
    core ? block("## Core questions to prepare", core) : "",
    keep ? block("## Expressions worth keeping", keep) : "",
    review ? block("## Session review", review) : "",
  )}\n`;
}
