import { sessionHeading } from "@/components/study-view";
import type { PackageBookmarks, StudyMaterials } from "@/lib/types";

// Every section this document can carry is optional at runtime, and empty is
// the normal case rather than the edge one: the generator drops any model
// answer whose quotes it cannot find in the candidate's own words, and a
// package scored before the coaching pass has no insights to draw priority
// expressions from. So sections render only when they say something —
// report-markdown.ts takes the same line, for the same reason. A bare
// "## Answers to memorize" with nothing under it reads as a file that failed
// to save rather than as a guide with nothing to memorise yet.
const GENERATED_NOTE = "_Generated by flightcheck from your session material._";

const block = (...parts: string[]): string => parts.filter(Boolean).join("\n\n");

export function studyMarkdown(
  doc: StudyMaterials,
  bookmarks: PackageBookmarks | null,
  meta: { roleTitle: string | null; generatedAt: string },
): string {
  const problems = doc.summary.core_problems
    .map((problem) => block(`### ${problem.title}`, problem.description))
    .join("\n\n");
  const strategy = doc.summary.improvement_strategy
    .map((step, index) => `${index + 1}. ${step}`)
    .join("\n");
  const expressions = doc.summary.priority_expressions
    .map((expression) => `> ${expression}`)
    .join("\n\n");
  const stand = block(
    problems,
    strategy ? block("### Improvement strategy", strategy) : "",
    expressions ? block("### Priority expressions", expressions) : "",
  );

  const saved = (bookmarks?.sessions ?? [])
    .filter((session) => session.items.length > 0)
    .map((session) => block(
      `### ${sessionHeading(session.session_index)}`,
      ...session.items.map((item) => block(
        `> ${item.source_quote}`,
        `Stronger: ${item.suggestion}`,
        `Why: ${item.why}`,
      )),
    ))
    .join("\n\n");

  const answers = doc.jd_core_answers
    .map((answer) => block(
      `### ${answer.question}`,
      answer.model_answer,
      ...answer.based_on_quotes.map((quote) => `> ${quote}`),
    ))
    .join("\n\n");

  return `${block(
    `# ${meta.roleTitle ?? "Interview"} study guide`,
    `Generated ${meta.generatedAt}.`,
    stand ? block("## Where you stand", GENERATED_NOTE, stand) : "",
    saved ? block("## Saved from your sessions", saved) : "",
    answers ? block("## Answers to memorize", GENERATED_NOTE, answers) : "",
  )}\n`;
}
