// The markdown study guide. Two things matter and the rest is layout.
//
// 1. What the customer said is reproduced verbatim. This file is the artifact
//    they take away and rehearse from; a quote that drifts is a quote they
//    will practise saying wrong.
// 2. Model-written sections are labelled as model-written. A month later
//    nothing on disk distinguishes "the answer I wrote" from "the answer a
//    model wrote for me" except this label.
import { describe, expect, it } from "vitest";

import { studyMarkdown } from "@/lib/study-markdown";
import type { PackageBookmarks, StudyMaterials } from "@/lib/types";

const SAVED_QUOTE = "we shipped it in six weeks with two engineers";

const doc = (overrides: Partial<StudyMaterials> = {}): StudyMaterials => ({
  schema_version: 1,
  source_session_ids: ["sess-1"],
  summary: {
    core_problems: [{
      title: "Answers stay abstract",
      description: "Examples arrive without the number behind them.",
      dimension_keys: ["structured-answers"],
    }],
    improvement_strategy: ["Name the metric first.", "Rehearse the close."],
    priority_expressions: ["cutting handle time by 18%"],
  },
  jd_core_answers: [{
    question: "Walk me through a project you led end to end.",
    dimension_key: "structured-answers",
    model_answer: "Open with the outcome, then the mechanism.",
    based_on_quotes: [SAVED_QUOTE],
  }],
  ...overrides,
});

const bookmarks = (): PackageBookmarks => ({
  package_id: "pkg-1",
  sessions: [{
    session_id: "sess-1",
    session_index: 2,
    items: [{
      turn_index: 4,
      verdict: "improve",
      source_quote: SAVED_QUOTE,
      suggestion: "We shipped in six weeks with a team of two.",
      why: "The constraint is the impressive part; lead with it.",
    }],
  }],
});

const meta = { roleTitle: "Forward Deployed Product Manager", generatedAt: "2026-08-08" };

const empty = (): StudyMaterials => doc({
  summary: { core_problems: [], improvement_strategy: [], priority_expressions: [] },
  jd_core_answers: [],
});

describe("what the guide contains", () => {
  it("reproduces saved expressions verbatim", () => {
    expect(studyMarkdown(doc(), bookmarks(), meta)).toContain(SAVED_QUOTE);
  });

  it("carries the role and the date it was built", () => {
    const output = studyMarkdown(doc(), bookmarks(), meta);

    expect(output.startsWith("# Forward Deployed Product Manager study guide")).toBe(true);
    expect(output).toContain("Generated 2026-08-08.");
  });

  it("names every section a reader needs to navigate", () => {
    const output = studyMarkdown(doc(), bookmarks(), meta);

    expect(output).toContain("## Where you stand");
    expect(output).toContain("## Saved from your sessions");
    expect(output).toContain("## Answers to memorize");
    expect(output).toContain("### Session 02");
  });

  it("numbers the improvement strategy in the order it was given", () => {
    const output = studyMarkdown(doc(), bookmarks(), meta);

    expect(output).toContain("1. Name the metric first.");
    expect(output).toContain("2. Rehearse the close.");
  });

  it("labels the model-written sections as generated", () => {
    const output = studyMarkdown(doc(), bookmarks(), meta);
    const label = /_Generated by flightcheck from your session material\._/g;

    // Both generated sections, and not the saved-expressions section — those
    // are the customer's own words.
    expect(output.match(label)).toHaveLength(2);
  });

  it("falls back to a neutral title when the rubric named no role", () => {
    expect(studyMarkdown(doc(), null, { ...meta, roleTitle: null }))
      .toContain("# Interview study guide");
  });
});

describe("sections render only when they say something", () => {
  it("omits the saved section when nothing was bookmarked", () => {
    const output = studyMarkdown(doc(), null, meta);

    expect(output).not.toContain("## Saved from your sessions");
    expect(output).toContain("## Answers to memorize");
  });

  it("omits the saved section when the join returned only empty sessions", () => {
    const output = studyMarkdown(doc(), { package_id: "pkg-1", sessions: [
      { session_id: "sess-1", session_index: 1, items: [] },
    ] }, meta);

    expect(output).not.toContain("## Saved from your sessions");
    expect(output).not.toContain("### Session 01");
  });

  it("omits the answers section when every answer was dropped as ungrounded", () => {
    // The routine case, not a rare one: the generator drops any answer whose
    // quotes it cannot find in what the candidate actually said.
    const output = studyMarkdown(doc({ jd_core_answers: [] }), bookmarks(), meta);

    expect(output).not.toContain("## Answers to memorize");
    expect(output).toContain("## Saved from your sessions");
  });

  it("omits the strategy and expression headings when those lists are empty", () => {
    const output = studyMarkdown(
      doc({ summary: { ...doc().summary, improvement_strategy: [], priority_expressions: [] } }),
      null, meta,
    );

    expect(output).toContain("## Where you stand");
    expect(output).not.toContain("### Improvement strategy");
    expect(output).not.toContain("### Priority expressions");
  });

  it("leaves no dangling heading when the guide is empty end to end", () => {
    const output = studyMarkdown(empty(), null, meta);

    expect(output).not.toContain("## Where you stand");
    expect(output).not.toContain("## Saved from your sessions");
    expect(output).not.toContain("## Answers to memorize");
    expect(output.trim()).toBe(
      "# Forward Deployed Product Manager study guide\n\nGenerated 2026-08-08.",
    );
  });

  it("still renders the saved section when only bookmarks survive", () => {
    // A customer who has saved phrases but whose generated guide came back
    // empty still has something worth downloading.
    const output = studyMarkdown(empty(), bookmarks(), meta);

    expect(output).toContain("## Saved from your sessions");
    expect(output).toContain(SAVED_QUOTE);
  });
});

describe("the file's shape", () => {
  it("ends with exactly one newline and never a run of blank lines", () => {
    // Blank-line runs are what a template that concatenates optional sections
    // produces when one of them is empty.
    const output = studyMarkdown(doc(), bookmarks(), meta);

    expect(output.endsWith("\n")).toBe(true);
    expect(output.endsWith("\n\n")).toBe(false);
    expect(output).not.toMatch(/\n{3,}/);
  });

  it("has no blank-line runs when sections are missing either", () => {
    expect(studyMarkdown(doc({ jd_core_answers: [] }), null, meta)).not.toMatch(/\n{3,}/);
  });
});
