import { sessionHeading } from "@/components/study-view";
import type { PackageBookmarks, StudyMaterials } from "@/lib/types";

export function studyMarkdown(
  doc: StudyMaterials,
  bookmarks: PackageBookmarks | null,
  meta: { roleTitle: string | null; generatedAt: string },
): string {
  const lines = [`# ${meta.roleTitle ?? "Interview"} study guide`, "", `Generated ${meta.generatedAt}.`, "", "## Summary", "", "_Generated by flightcheck._", ""];
  for (const problem of doc.summary.core_problems) lines.push(`### ${problem.title}`, "", problem.description, "");
  lines.push("### Improvement strategy", "");
  doc.summary.improvement_strategy.forEach((step, index) => lines.push(`${index + 1}. ${step}`));
  lines.push("", "### Priority expressions", "", ...doc.summary.priority_expressions.map((item) => `> ${item}`), "", "## Saved from your sessions", "");
  for (const session of bookmarks?.sessions ?? []) {
    lines.push(`### ${sessionHeading(session.session_index)}`, "");
    for (const item of session.items) lines.push(`> ${item.source_quote}`, "", `Stronger: ${item.suggestion}`, "", `Why: ${item.why}`, "");
  }
  lines.push("## Answers to memorize", "", "_Generated by flightcheck from your session material._", "");
  for (const answer of doc.jd_core_answers) {
    lines.push(`### ${answer.question}`, "", answer.model_answer, "");
    answer.based_on_quotes.forEach((quote) => lines.push(`> ${quote}`, ""));
  }
  return `${lines.join("\n").trim()}\n`;
}
