"""Tests for tools/backup_corpus.py -- the corpus bucket's only backup.

The corpus is the one asset in this system with no second copy anywhere.
Postgres has Supabase's point-in-time backups; recordings can be
regenerated by running another session; the corpus cannot. It is not in
git (workspace confidentiality rule), it was assembled by hand, and losing
it degrades every rubric compiled from that moment on -- silently, because
a missing corpus produces "(no corpus documents provided)" rubrics with no
error and no log line.

So the offline core is under test, against a fake bucket: which objects are
selected, what the manifest says, that a restore is a dry run unless told
otherwise, and that neither direction can silently write over something.
The Supabase client construction in main() is thin wiring, exercised
manually (house pattern, matching test_purge_user.py).
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from backup_corpus import (
    EmptyCorpusError,
    backup_corpus,
    build_parser,
    corpus_entries,
    dated_backup_dir,
    manifest_lines,
    restore_corpus,
)


class FakeBucket:
    """Supabase storage bucket stand-in: prefix listing, download, upload.

    Mirrors the real API's non-recursive listing -- bucket.list() returns
    root entries plus a folder entry, and bucket.list("fewshot") returns
    bare names under that prefix.
    """

    def __init__(self, files: dict[str, bytes] | None = None,
                 download_errors: set[str] | None = None):
        self.files: dict[str, bytes] = dict(files or {})
        self.download_errors = set(download_errors or set())
        self.uploads: list[tuple[str, bytes]] = []

    def list(self, path: str = "") -> list[dict]:
        if path:
            prefix = f"{path}/"
            return [{"name": name[len(prefix):]} for name in sorted(self.files)
                    if name.startswith(prefix)]
        entries = [{"name": name} for name in sorted(self.files)
                   if "/" not in name]
        folders = sorted({name.split("/", 1)[0] for name in self.files
                          if "/" in name})
        return entries + [{"name": folder} for folder in folders]

    def download(self, name: str) -> bytes:
        if name in self.download_errors:
            raise RuntimeError(f"download failed: {name}")
        return self.files[name]

    def upload(self, path: str, file: bytes, file_options: dict | None = None):
        self.uploads.append((path, file))
        self.files[path] = file


def _bucket() -> FakeBucket:
    return FakeBucket({
        "fdpm-role-bar.md": b"# the bar\n",
        "interview-signals.md": b"# signals\n",
        "notes.txt": b"scratch",                    # not a corpus doc
        "fewshot/strong-rubric.json": b'{"a": 1}',
        "fewshot/weak-rubric.json": b'{"b": 2}',
        "fewshot/README.md": b"not a fewshot",      # wrong extension here
    })


# --- selection ----------------------------------------------------------------


def test_entries_take_root_markdown_and_fewshot_json_only():
    # Exactly what SupabaseStorage.sync_corpus reads back. A backup that
    # captures more or less than the reader consumes is not a backup of the
    # thing that matters.
    assert corpus_entries(_bucket()) == [
        "fdpm-role-bar.md",
        "fewshot/strong-rubric.json",
        "fewshot/weak-rubric.json",
        "interview-signals.md",
    ]


def test_entries_of_an_empty_bucket_are_empty():
    assert corpus_entries(FakeBucket()) == []


def test_the_folder_entry_is_not_mistaken_for_a_document():
    # Supabase's root listing includes a bare "fewshot" entry for the
    # subdirectory; downloading it would fail, not back anything up.
    assert "fewshot" not in corpus_entries(_bucket())


# --- the manifest -------------------------------------------------------------


def test_manifest_is_in_shasum_check_format():
    # Written so `shasum -a 256 -c MANIFEST.sha256` verifies a restore with a
    # tool the operator already has, under pressure, without this repo.
    lines = manifest_lines({"a.md": b"hello", "b/c.json": b"{}"})
    digest = hashlib.sha256(b"hello").hexdigest()
    assert lines[0] == f"{digest}  a.md"
    assert lines == sorted(lines, key=lambda line: line.split("  ", 1)[1])


# --- backup -------------------------------------------------------------------


def test_backup_writes_every_document_and_a_manifest(tmp_path):
    result = backup_corpus(_bucket(), tmp_path / "corpus-2026-08-03")

    root = tmp_path / "corpus-2026-08-03"
    assert (root / "fdpm-role-bar.md").read_bytes() == b"# the bar\n"
    assert (root / "fewshot" / "strong-rubric.json").read_bytes() == b'{"a": 1}'
    assert (root / "MANIFEST.sha256").exists()
    assert result.document_count == 4
    assert result.byte_count == sum(
        len(_bucket().files[name]) for name in corpus_entries(_bucket()))


def test_the_manifest_verifies_against_the_files_just_written(tmp_path):
    dest = tmp_path / "corpus"
    backup_corpus(_bucket(), dest)

    for line in (dest / "MANIFEST.sha256").read_text().splitlines():
        digest, name = line.split("  ", 1)
        assert hashlib.sha256((dest / name).read_bytes()).hexdigest() == digest


def test_backup_refuses_to_write_into_an_existing_directory(tmp_path):
    # A half-overwritten backup is worse than no backup: it looks complete.
    dest = tmp_path / "corpus"
    dest.mkdir()

    with pytest.raises(FileExistsError):
        backup_corpus(_bucket(), dest)


def test_a_download_that_fails_aborts_loudly_rather_than_writing_a_short_backup(tmp_path):
    bucket = _bucket()
    bucket.download_errors.add("interview-signals.md")

    with pytest.raises(RuntimeError):
        backup_corpus(bucket, tmp_path / "corpus")

    # No manifest means no claim of completeness. A directory of some of the
    # corpus, blessed by a manifest, is the failure mode worth preventing.
    assert not (tmp_path / "corpus" / "MANIFEST.sha256").exists()


def test_backing_up_an_empty_bucket_raises_instead_of_writing_a_decoy(tmp_path):
    # An empty corpus bucket is either a brand-new project or the disaster
    # this tool exists for. Writing `corpus-2026-08-03/` with an empty
    # manifest into the backup folder would leave something that reads as a
    # backup six months later and restores nothing.
    with pytest.raises(EmptyCorpusError):
        backup_corpus(FakeBucket(), tmp_path / "corpus")

    assert not (tmp_path / "corpus").exists()


def test_dated_backup_dir_sorts_and_never_collides():
    from datetime import UTC, datetime

    when = datetime(2026, 8, 3, 22, 15, tzinfo=UTC)
    assert dated_backup_dir(Path("/backups"), when) == Path("/backups/corpus-2026-08-03")


# --- restore ------------------------------------------------------------------


def test_restore_plans_every_document_without_uploading_by_default(tmp_path):
    source = tmp_path / "corpus"
    backup_corpus(_bucket(), source)
    target = FakeBucket()

    result = restore_corpus(target, source, execute=False)

    assert result.document_count == 4
    assert target.uploads == []          # dry run touched nothing


def test_restore_uploads_with_the_bucket_relative_paths_intact(tmp_path):
    source = tmp_path / "corpus"
    backup_corpus(_bucket(), source)
    target = FakeBucket()

    restore_corpus(target, source, execute=True)

    uploaded = dict(target.uploads)
    assert set(uploaded) == {
        "fdpm-role-bar.md", "interview-signals.md",
        "fewshot/strong-rubric.json", "fewshot/weak-rubric.json",
    }
    assert uploaded["fewshot/strong-rubric.json"] == b'{"a": 1}'


def test_restore_refuses_a_directory_whose_manifest_does_not_match(tmp_path):
    source = tmp_path / "corpus"
    backup_corpus(_bucket(), source)
    (source / "fdpm-role-bar.md").write_bytes(b"tampered")

    # Restoring a corrupted backup over a live bucket is unrecoverable: the
    # bucket WAS the other copy.
    with pytest.raises(ValueError, match=r"fdpm-role-bar\.md"):
        restore_corpus(FakeBucket(), source, execute=True)


def test_restore_refuses_a_directory_with_no_manifest(tmp_path):
    source = tmp_path / "loose-files"
    source.mkdir()
    (source / "something.md").write_bytes(b"x")

    with pytest.raises(FileNotFoundError):
        restore_corpus(FakeBucket(), source, execute=True)


def test_a_dry_run_still_verifies_the_manifest(tmp_path):
    source = tmp_path / "corpus"
    backup_corpus(_bucket(), source)
    (source / "fdpm-role-bar.md").write_bytes(b"tampered")

    # Finding out at --execute time is finding out too late.
    with pytest.raises(ValueError):
        restore_corpus(FakeBucket(), source, execute=False)


# --- the CLI contract ---------------------------------------------------------


def test_parser_requires_a_command():
    with pytest.raises(SystemExit):
        build_parser().parse_args([])


def test_backup_requires_a_destination():
    with pytest.raises(SystemExit):
        build_parser().parse_args(["backup"])


def test_restore_defaults_to_a_dry_run():
    args = build_parser().parse_args(["restore", "--from", "some/dir"])
    assert args.execute is False


def test_backup_has_no_execute_switch_to_forget():
    # A backup is not destructive; making the operator pass a flag to take
    # one is friction with no safety behind it.
    args = build_parser().parse_args(["backup", "--dest", "some/dir"])
    assert not hasattr(args, "execute") or args.execute is None
