"""Write a dated real-usage report into docs/metrics/ (F-13).

Manual operator tool, never part of the app or the gates. It reads
GET /api/metrics/usage from the deployed worker and renders it as a
markdown file of record, the same way evals reports are committed with
their provenance.

The rendering is where the value is. This repo has a standing rule that a
metrics report states its sample size and says plainly when the sample is
the operator rather than customers, and impression rule (7) fails a
release whose numbers read like customer data when they are self-test
data. So every rate here is printed with the counts behind it, the number
of distinct accounts is stated in the first line of the summary, and a
one-account sample gets an explicit "these are self-test numbers" banner
that cannot be forgotten because it is generated from the data rather than
typed by whoever runs the tool.

A metric the product does not instrument is printed as "not instrumented"
with the reason, never as a dash the reader is free to interpret.

Usage (from services/scorer, env from .env):
    uv run python tools/usage_report.py --worker-url https://worker.example
    uv run python tools/usage_report.py --worker-url ... --out ../../docs/metrics
"""
from __future__ import annotations

import argparse
from datetime import UTC, date, datetime
from pathlib import Path

import httpx

from scorer.api.usage import UsageMetrics
from scorer.env import load_env, require_key

# services/scorer/tools/usage_report.py -> repo root.
REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUT_DIR = REPO_ROOT / "docs" / "metrics"
_TIMEOUT_S = 30.0

SELF_TEST_BANNER = (
    "> **These are self-test numbers, not customer usage.** Every session in "
    "this sample was run by the operator on a single account. They are "
    "published to show the measurement works, not to claim adoption."
)


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def _seconds(value: float | None) -> str:
    return "not measured" if value is None else f"{value:.2f}s"


def render_report(usage: UsageMetrics, *, generated_on: date,
                  source: str) -> str:
    """The markdown report. Pure, so its honesty is under test."""
    lines: list[str] = [
        f"# Real-usage metrics — {generated_on.isoformat()}",
        "",
        f"Source: `{source}`. Generated by `services/scorer/tools/usage_report.py`.",
        "",
        (f"**Sample: {usage.sessions_started} started sessions across "
         f"{usage.packages_sampled} packages and {usage.distinct_users} "
         f"distinct account(s).**"),
        "",
    ]
    if usage.distinct_users <= 1:
        lines += [SELF_TEST_BANNER, ""]
    if usage.sessions_started == 0:
        lines += [
            "No sessions have been started yet, so every rate below is zero "
            "rather than unknown. The numbers become meaningful with the "
            "first external pilot.",
            "",
        ]

    lines += [
        "## PRD success metrics",
        "",
        "| Metric | Target | Observed | Sample |",
        "| --- | --- | --- | --- |",
        (f"| Session completion rate | >= 85% | "
         f"{_pct(usage.session_completion_rate)} | "
         f"{usage.sessions_completed}/{usage.sessions_started} sessions |"),
        ("| First-response latency (p50) | <= 800 ms | not instrumented | "
         "n/a |"),
        (f"| Package utilization | >= 4 of 6 | "
         f"{usage.package_burn_through:.2f} sessions | "
         f"{usage.packages_sampled} packages |"),
        "",
        "## Other measured figures",
        "",
        "| Figure | Observed | Sample |",
        "| --- | --- | --- |",
        (f"| Scoring latency (p50) | {_seconds(usage.p50_scoring_latency_s)} "
         f"| {usage.scoring_latency_sample} runs |"),
        (f"| Candidate response latency (p50) | "
         f"{_seconds(usage.p50_candidate_response_s)} | "
         f"{usage.candidate_response_sample} sessions |"),
        (f"| Package burn-through (ratio) | "
         f"{_pct(usage.package_burn_through_ratio)} of available sessions | "
         f"{usage.packages_sampled} packages |"),
        (f"| Paid packages in sample | {usage.paid_packages_sampled} | "
         f"of {usage.packages_sampled} |"),
        "",
        "## What these numbers do not say",
        "",
    ]
    lines += [f"- {note}" for note in usage.notes]
    lines += [
        "",
        "Definitions, so the rates can be checked against the rows:",
        "",
        "- **Started**: a session the pipeline has seen, or one the browser "
        "connected to at least once. A planned session nobody entered is an "
        "unused slot, not an abandonment.",
        "- **Completed**: status `scored` or `insufficient` — the session ran "
        "to the end and uploaded; `insufficient` means the recording was too "
        "short to score, not that it failed.",
        "- **Package utilization**: mean slots consumed per package, where a "
        "failed or insufficient session keeps its slot.",
        "",
    ]
    return "\n".join(lines)


def fetch_usage(worker_url: str, token: str) -> UsageMetrics:
    """Read the deployed worker's usage endpoint."""
    response = httpx.get(
        f"{worker_url.rstrip('/')}/api/metrics/usage",
        headers={"Authorization": f"Bearer {token}"},
        timeout=_TIMEOUT_S,
    )
    response.raise_for_status()
    return UsageMetrics.model_validate(response.json())


def report_path(out_dir: Path, generated_on: date) -> Path:
    return Path(out_dir) / f"{generated_on.isoformat()}-usage.md"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="usage_report",
        description="Write a dated real-usage report into docs/metrics/.",
    )
    parser.add_argument("--worker-url", required=True,
                        help="base URL of the deployed scorer worker")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--date", default=None,
                        help="report date (YYYY-MM-DD); defaults to today UTC")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    load_env()
    token = require_key("WORKER_API_TOKEN")
    generated_on = (date.fromisoformat(args.date) if args.date
                    else datetime.now(UTC).date())
    usage = fetch_usage(args.worker_url, token)
    destination = report_path(args.out, generated_on)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        render_report(usage, generated_on=generated_on, source=args.worker_url))
    print(f"wrote {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
