import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

import type { QaSet, SessionStudyMeta } from "@/lib/session-study";
import type { SessionInsights } from "@/lib/types";

const WHITE = "#ffffff";
const INK = "#171717";
const MUTED_INK = "#555555";
const QUOTE_INK = "#333333";
const RULE = "#aaaaaa";
const styles = StyleSheet.create({
  page: { backgroundColor: WHITE, color: INK, fontFamily: "Helvetica", fontSize: 10, lineHeight: 1.45, padding: 42 },
  title: { fontFamily: "Helvetica-Bold", fontSize: 20 },
  context: { color: MUTED_INK, marginBottom: 16 },
  section: { marginTop: 16 },
  heading: { fontFamily: "Helvetica-Bold", fontSize: 12, marginBottom: 5 },
  subheading: { fontFamily: "Helvetica-Bold", marginTop: 7 },
  item: { marginBottom: 3 },
  quote: { borderLeftColor: RULE, borderLeftWidth: 1, color: QUOTE_INK, marginTop: 4, paddingLeft: 8 },
  footer: { borderTopColor: RULE, borderTopWidth: 1, color: MUTED_INK, marginTop: 20, paddingTop: 8 },
});

export default function StudyPdf({ sets, insights, meta }: { sets: QaSet[]; insights: SessionInsights | null; meta: SessionStudyMeta }) {
  return <Document title={`flightcheck session ${meta.sessionNumber} study notes`}><Page size="A4" style={styles.page} wrap>
    <Text style={styles.title}>flightcheck study notes</Text>
    <Text style={styles.context}>Session {meta.sessionNumber} | {meta.sessionDate} | {meta.roleTitle ?? "Interview role"}</Text>
    {sets.map((set) => <View key={set.ordinal} style={styles.section}>
      <Text style={styles.heading}>Q. {set.question ?? "Question not captured"}</Text>
      <Text><Text style={styles.subheading}>Better answer. </Text>{set.better}</Text>
      <Text><Text style={styles.subheading}>What you said. </Text>{set.your_answer}</Text>
      <Text style={styles.context}>Why. {set.why}</Text>
    </View>)}
    {insights && insights.must_answer.length > 0 ? <View style={styles.section}><Text style={styles.heading}>Core questions to prepare</Text>{insights.must_answer.map((item) => <View key={item.question}><Text style={styles.subheading}>Q. {item.question}</Text><Text>{item.model_answer}</Text><Text style={styles.context}>Generated from your session material.</Text>{item.based_on_quotes.map((value) => <Text key={value} style={styles.quote}>{value}</Text>)}</View>)}</View> : null}
    {insights && insights.must_keep.length > 0 ? <View style={styles.section}><Text style={styles.heading}>Expressions worth keeping</Text>{insights.must_keep.map((item, index) => <View key={index}><Text style={styles.quote}>{item.said_verbatim}</Text><Text>{item.better}</Text><Text style={styles.context}>{item.why}</Text></View>)}</View> : null}
    {insights && (insights.did_well.length > 0 || insights.did_poorly.length > 0) ? <View style={styles.section}><Text style={styles.heading}>Session review</Text>{insights.did_well.length > 0 ? <><Text style={styles.subheading}>What went well</Text>{insights.did_well.map((item) => <Text key={item} style={styles.item}>• {item}</Text>)}</> : null}{insights.did_poorly.length > 0 ? <><Text style={styles.subheading}>What needs work</Text>{insights.did_poorly.map((item) => <Text key={item} style={styles.item}>• {item}</Text>)}</> : null}</View> : null}
    <Text style={styles.footer}>Generated by flightcheck on {meta.generatedDate}.</Text>
  </Page></Document>;
}
